# Generated by Django 5.0.2 on 2024-03-07 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppEntrega', '0003_addreceta_usuario_rename_estudiante_consulta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='addreceta',
            name='descripcion',
            field=models.CharField(blank=True, default='DEFAULT VALUE', max_length=240, null=True),
        ),
        migrations.AddField(
            model_name='addreceta',
            name='nombre_receta',
            field=models.CharField(default='', max_length=60),
        ),
    ]
